_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 17
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.9
            "8":
                - 5
            "10":
                - 3
            "12": 0.19.9
            "13": linux-x86_64
